version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '4200:80'
  prod:
    build: .
    ports:
      - '4200:80'
