FROM node:14-alpine AS setup
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
FROM nginx:1.13.12-alpine
COPY --from=setup /app/ /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 4200:80